export declare const GENRE_EMOJI: {
    액션: import("@emotion/react/jsx-runtime").JSX.Element;
    로맨스: import("@emotion/react/jsx-runtime").JSX.Element;
    코미디: import("@emotion/react/jsx-runtime").JSX.Element;
    드라마: import("@emotion/react/jsx-runtime").JSX.Element;
    범죄: import("@emotion/react/jsx-runtime").JSX.Element;
    다큐멘터리: import("@emotion/react/jsx-runtime").JSX.Element;
    애니메이션: import("@emotion/react/jsx-runtime").JSX.Element;
    음악: import("@emotion/react/jsx-runtime").JSX.Element;
    스릴러: import("@emotion/react/jsx-runtime").JSX.Element;
    호러: import("@emotion/react/jsx-runtime").JSX.Element;
    SF: import("@emotion/react/jsx-runtime").JSX.Element;
    판타지: import("@emotion/react/jsx-runtime").JSX.Element;
    모험: import("@emotion/react/jsx-runtime").JSX.Element;
    가족: import("@emotion/react/jsx-runtime").JSX.Element;
    역사: import("@emotion/react/jsx-runtime").JSX.Element;
    전쟁: import("@emotion/react/jsx-runtime").JSX.Element;
    "TV \uC601\uD654": import("@emotion/react/jsx-runtime").JSX.Element;
    미스터리: import("@emotion/react/jsx-runtime").JSX.Element;
    서부: import("@emotion/react/jsx-runtime").JSX.Element;
};
