export declare const wrapper: import("@emotion/react").SerializedStyles;
export declare const pageContainer: import("@emotion/react").SerializedStyles;
export declare const titleWrapper: import("@emotion/react").SerializedStyles;
export declare const titleContainer: import("@emotion/react").SerializedStyles;
export declare const title: import("@emotion/react").SerializedStyles;
export declare const subtitle: import("@emotion/react").SerializedStyles;
export declare const genreGroup: import("@emotion/react").SerializedStyles;
export declare const requiredBadge: import("@emotion/react").SerializedStyles;
export declare const genreGrid: import("@emotion/react").SerializedStyles;
export declare const genreButton: ($isSelected: boolean) => import("@emotion/react").SerializedStyles;
export declare const Warning: import("@emotion/react").SerializedStyles;
export declare const TextWrapper: import("@emotion/react").SerializedStyles;
