import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "@emotion/react/jsx-runtime";
import Search from "@assets/icons/search_small.svg?react";
import { useState } from "react";
import styles from "./index.styles";
function ReviewsOpertionPage() {
    const [filterValue, setFilterValue] = useState("all");
    const [toggled, setToggled] = useState(false);
    return (_jsxs(_Fragment, { children: [_jsxs("div", { css: styles.filterContainer(), children: [_jsxs("div", { css: styles.filter(), children: [_jsx("label", { htmlFor: "filter", children: "Filter By: " }), _jsxs("select", { id: "filter", value: filterValue, onChange: (event) => setFilterValue(event.target.value), children: [_jsx("option", { value: "all", children: "All" }), _jsx("option", { value: "user", children: "User" }), _jsx("option", { value: "critic", children: "Critic" }), _jsx("option", { value: "admin", children: "Admin" })] })] }), _jsxs("form", { css: styles.search(), onSubmit: (event) => event.preventDefault(), children: [_jsx("input", { type: "text" }), _jsx("button", { type: "submit", children: _jsx(Search, {}) })] })] }), _jsxs("table", { css: styles.tableContainer(), children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "movie" }), _jsx("th", { children: "user" }), _jsx("th", { children: "reviews" }), _jsx("th", { children: "hide" })] }) }), _jsx("tbody", { children: _jsxs("tr", { children: [_jsx("td", { css: styles.tableBodyItem(), children: _jsxs("div", { className: "movie-info", children: [_jsx("div", { className: "movie-info_thumbnail", children: _jsx("img", { src: "", alt: "" }) }), _jsxs("div", { className: "movie-info_detail", children: [_jsx("span", { className: "title", children: "Eternal Sunshine" }), _jsx("span", { className: "genre", children: "Romance" })] })] }) }), _jsx("td", { css: styles.tableBodyItem(), children: "Amanda" }), _jsx("td", { css: styles.tableBodyItem(), children: "\uBAA8\uB450 \uAE30\uC5B5 \uC783\uACE0 \uB2E4\uC2DC \uAE30\uC5B5 \uB418\uC0B4\uC544\uB098\uB294 \uC7AC\uBBF8\uC5C6\uB294 \uC601\uD654.." }), _jsx("td", { css: styles.tableBodyItem(), children: _jsx("button", { css: styles.toggleBtn(), onClick: () => setToggled(!toggled), className: toggled ? "toggled" : "", children: _jsx("div", { className: "thumb" }) }) })] }) })] })] }));
}
export default ReviewsOpertionPage;
