export declare const consentWrapper: import("@emotion/react").SerializedStyles;
export declare const textBase: import("@emotion/react").SerializedStyles;
export declare const wrapper: import("@emotion/react").SerializedStyles;
export declare const titleWrapper: import("@emotion/react").SerializedStyles;
export declare const titleContainer: import("@emotion/react").SerializedStyles;
export declare const title: import("@emotion/react").SerializedStyles;
export declare const requiredBadge: import("@emotion/react").SerializedStyles;
export declare const subtitle: import("@emotion/react").SerializedStyles;
export declare const pageIndicator: import("@emotion/react").SerializedStyles;
export declare const selectedCount: import("@emotion/react").SerializedStyles;
export declare const totalContainer: import("@emotion/react").SerializedStyles;
export declare const currentPage: import("@emotion/react").SerializedStyles;
export declare const totalPages: import("@emotion/react").SerializedStyles;
export declare const movieGridWrapper: import("@emotion/react").SerializedStyles;
export declare const movieGrid: import("@emotion/react").SerializedStyles;
export declare const movieCard: ($isSelected: boolean) => import("@emotion/react").SerializedStyles;
export declare const movieImage: ($isSelected: boolean) => import("@emotion/react").SerializedStyles;
export declare const movieTitle: import("@emotion/react").SerializedStyles;
export declare const checkIcon: ($isVisible: boolean) => import("@emotion/react").SerializedStyles;
export declare const arrowButton: import("@emotion/react").SerializedStyles;
export declare const Warning: import("@emotion/react").SerializedStyles;
export declare const previousButton: import("@emotion/react").SerializedStyles;
export declare const nextButton: import("@emotion/react").SerializedStyles;
export declare const TextWrapper: import("@emotion/react").SerializedStyles;
