import { SerializedStyles } from "@emotion/react";
declare const _default: {
    titleHeaderContainer(): SerializedStyles;
    reportContainer(): SerializedStyles;
    reportCard(): SerializedStyles;
    line(): SerializedStyles;
    reportCardHeader(): SerializedStyles;
    profilePanel(): SerializedStyles;
    status(status?: boolean): SerializedStyles;
    reportInfoContainer(): SerializedStyles;
    reportMessageBox(): SerializedStyles;
    toggleBtn(): SerializedStyles;
    miniToggleBtn(): SerializedStyles;
    swiperContainer(): SerializedStyles;
    commentContainer(): SerializedStyles;
    modalOuterContainer(): SerializedStyles;
    modalContainer(): SerializedStyles;
    modalHeader(): SerializedStyles;
    modalContent(): SerializedStyles;
    modalCommentCard(): SerializedStyles;
};
export default _default;
