export const routeConfig = [
  { path: "/", header: "Main", gnb: true, margin: "60px 0" },
  { path: "/auth/sign-in", header: "", gnb: false, margin: "0" },
  { path: "/auth/sign-up", header: "", gnb: false, margin: "0" },
  { path: "/user/:nickname", header: "Main", gnb: true, margin: "60px 0" },
  {
    path: "/user/:nickname/edit",
    header: "Label",
    gnb: false,
    margin: "60px 0 0 0",
  },
  { path: "/movie/:id", header: "", gnb: true, margin: "0 0 60px 0" },
  { path: "/movie/:id/review", header: "", gnb: true, margin: "0 0 60px 0" },
  { path: "/movie-log", header: "Main", gnb: true, margin: "60px 0" },
  {
    path: "/movie-log/detail/:boardId",
    header: "Label",
    gnb: false,
    margin: "60px 0 0 0",
  },
  { path: "/movie-log/add", header: "", gnb: false, margin: "0" },
  { path: "/movie-log/edit", header: "", gnb: false, margin: "0" },
  { path: "/picky", header: "Main", gnb: true, margin: "60px 0" },
  {
    path: "/genre/:genreId",
    header: "Label",
    gnb: false,
    margin: "60px 0 0 0",
  },
  { path: "/notification", header: "Label", gnb: false, margin: "60px 0 0 0" },
  { path: "/recommendation", header: "Main", gnb: true, margin: "60px 0" },
  { path: "/search", header: "Main", gnb: false, margin: "60px 0 0 0" },
  { path: "/error", header: "", gnb: false, margin: "0" },
];
