export declare const wrapper: import("@emotion/react").SerializedStyles;
export declare const backWrapper: import("@emotion/react").SerializedStyles;
export declare const progressBarContainer: import("@emotion/react").SerializedStyles;
export declare const progressStyle: (progress: number) => import("@emotion/react").SerializedStyles;
export declare const responsiveFlexBox: import("@emotion/react").SerializedStyles;
export declare const responsiveButtonWrapper: import("@emotion/react").SerializedStyles;
export declare const backButtonWrapper: import("@emotion/react").SerializedStyles;
export declare const backButton: import("@emotion/react").SerializedStyles;
export declare const backButtonStyle: import("@emotion/react").SerializedStyles;
export declare const logoContainer: import("@emotion/react").SerializedStyles;
export declare const block: {
    FlexBox: ({ $direction, $justifyContent, $alignItems, $width, $height, $margin, $padding, $border, $borderRadius, $bgColor, $gap, $pointer, }: StyleBlock) => import("@emotion/react").SerializedStyles;
};
type StyleBlock = {
    $width?: string;
    $height?: string;
    $margin?: string;
    $padding?: string;
    $direction?: string;
    $justifyContent?: string;
    $alignItems?: string;
    $border?: string;
    $borderRadius?: string;
    $bgColor?: string;
    $gap?: string;
    $pointer?: boolean;
};
export declare const slideWrapper: import("@emotion/react").SerializedStyles;
export declare const slideContent: (step: number) => import("@emotion/react").SerializedStyles;
export declare const slideNext: import("@emotion/react").SerializedStyles;
export declare const slidePrev: import("@emotion/react").SerializedStyles;
export declare const slideIn: import("@emotion/react").SerializedStyles;
export declare const slideOut: import("@emotion/react").SerializedStyles;
export {};
